/* GENERATED by tools/ui_kit/make_icons.py — do not edit by hand. */
#pragma once
#include "lvgl.h"

/* Line icons for the UI kit, as recolourable 4-bit alpha images. */
typedef enum {
    UK_ICON_LAYOUTS,
    UK_ICON_SUN,
    UK_ICON_MOON,
    UK_ICON_REC,
    UK_ICON_GEAR,
    UK_ICON_CAR,
    UK_ICON_CAN,
    UK_ICON_OBD,
    UK_ICON_WIFI,
    UK_ICON_CHART,
    UK_ICON_PLAY,
    UK_ICON_INFO,
    UK_ICON_LEFT,
    UK_ICON_RIGHT,
    UK_ICON_CLOSE,
    UK_ICON_CHECK,
    UK_ICON_IMAGE,
    UK_ICON_GAUGE,
    UK_ICON_CHANNELS,
    UK_ICON_WEB,
    UK_ICON_PEAK,
    UK_ICON_WRENCH,
    UK_ICON_BACK,
    UK_ICON_QR,
    UK_ICON_CHIP,
    UK_ICON_ROUTE,
    UK_ICON_SHIFTER,
    UK_ICON_SPARK,
    UK_ICON_RESET,
    UK_ICON_ALERT,
    UK_ICON_UPDATE,
    UK_ICON_CARD,
    UK_ICON_DIM,
    UK_ICON_STOP,
    UK_ICON_PLUS,
    UK_ICON_LIST,
    UK_ICON_CLOCK,
    UK_ICON_HOTSPOT,
    UK_ICON_TRASH,
    UK_ICON_KEYPAD,
    UK_ICON__COUNT,
    UK_ICON_NONE = -1,
} uk_icon_t;

typedef enum {
    UK_ICON_MD = 0,   /* 22 px — buttons, rows, the dock */
    UK_ICON_LG = 1,   /* 32 px — tiles */
} uk_icon_size_t;

#define UK_ICON_PX_MD 22
#define UK_ICON_PX_LG 32

const lv_img_dsc_t *uk_icon_img(uk_icon_t icon, uk_icon_size_t size);

