// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Dashboard Design 8.3.11

#include "../ui.h"
#include "../theme.h"


// COMPONENT Slider2

lv_obj_t * ui_Slider2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Slider2;
    cui_Slider2 = lv_slider_create(comp_parent);
    lv_slider_set_range(cui_Slider2, 0, 7000);
    lv_slider_set_value(cui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider2, 766);
    lv_obj_set_height(cui_Slider2, 84);
    lv_obj_set_x(cui_Slider2, 2);
    lv_obj_set_y(cui_Slider2, -195);
    lv_obj_set_align(cui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider2, THEME_COLOR_TEXT_PRIMARY, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider2, THEME_COLOR_TEXT_PRIMARY, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(cui_Slider2, &ui__temporary_image, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider2, THEME_COLOR_TEXT_PRIMARY, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SLIDER2_NUM);
    children[UI_COMP_SLIDER2_SLIDER2] = cui_Slider2;
    lv_obj_add_event_cb(cui_Slider2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Slider2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Slider2_create_hook(cui_Slider2);
    return cui_Slider2;
}

