// This file was generated by SquareLine Studio
#include "../ui.h"
#include "../theme.h"
#include "esp_log.h"
#include "driver/twai.h"
#include "misc/lv_color.h"
#include <math.h>  // For sin function in data generation (optional)

static const char *TAG = "ui_Screen2";

static lv_obj_t *knock_chart;
static lv_chart_series_t *knock_series;
static lv_obj_t *knock_threshold_label;  // New label for Knock 1 threshold value
lv_obj_t *ui_band_freq_dropdown;
lv_obj_t *ui_gain_dropdown;
lv_obj_t *ui_time_constant_dropdown;

// Function to send CAN messages for knock settings
void send_knock_setting_can_message(uint32_t can_id, uint8_t value) {
    twai_message_t message = {};
    message.identifier = can_id;
    message.extd = 0;
    message.data_length_code = 1;
    message.data[0] = value;

    if (twai_transmit(&message, pdMS_TO_TICKS(100)) == ESP_OK) {
        //ESP_LOGI(TAG, "CAN message sent: CAN ID 0x%X, Value: %u", can_id, value);
    } else {
        ESP_LOGE(TAG, "Failed to send CAN message");
    }
}

// Dropdown event callback
static void dropdown_event_handler(lv_event_t *e) {
    lv_obj_t *dropdown = lv_event_get_target(e);
    uint16_t selected = lv_dropdown_get_selected(dropdown);

    // Determine which dropdown triggered the event and send corresponding CAN message
    if (dropdown == ui_band_freq_dropdown) {
        send_knock_setting_can_message(0x200, (uint8_t)selected); // CAN ID 0x200 for Band Pass Frequency
    } else if (dropdown == ui_gain_dropdown) {
        send_knock_setting_can_message(0x201, (uint8_t)(0x80 + selected)); // CAN ID 0x201 for Gain
    } else if (dropdown == ui_time_constant_dropdown) {
        send_knock_setting_can_message(0x202, (uint8_t)(0xC0 + selected)); // CAN ID 0x202 for Time Constants
    }
}

void create_knock_graph_on_screen2(lv_obj_t *parent) {
    // Create a chart object and set its size and alignment
    knock_chart = lv_chart_create(parent);
    
    // Set the background color of the chart
    lv_obj_set_style_bg_color(knock_chart, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_border_color(knock_chart, THEME_COLOR_CHART_BORDER, LV_PART_MAIN);

    // Set the chart size
    lv_obj_set_size(knock_chart, 500, 370);

    // Align the chart to the right side of the parent
    lv_obj_align(knock_chart, LV_ALIGN_RIGHT_MID, -20, 0);

    // Set chart type to line
    lv_chart_set_type(knock_chart, LV_CHART_TYPE_LINE);

    // Set the number of points on the chart
    lv_chart_set_point_count(knock_chart, 40); // Adjust for smoother rendering

    // Set the Y-axis range to 0-100
    lv_chart_set_range(knock_chart, LV_CHART_AXIS_PRIMARY_Y, 0, 100);

    // Set up chart divisions
    lv_chart_set_div_line_count(knock_chart, 11, 6);
    lv_chart_set_axis_tick(knock_chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 5, true, 50);

    // Customize series style for smooth rendering
    knock_series = lv_chart_add_series(knock_chart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);

    // Set series line width for smoother visual
    lv_obj_set_style_line_width(knock_chart, 3, LV_PART_ITEMS);  // Adjust line thickness
    lv_obj_set_style_line_color(knock_chart, lv_palette_main(LV_PALETTE_RED), LV_PART_ITEMS);
    lv_obj_set_style_line_color(knock_chart, THEME_COLOR_BORDER_MED, LV_PART_MAIN);
    lv_obj_set_style_border_color(knock_chart, THEME_COLOR_BORDER_MED, LV_PART_MAIN);
    lv_obj_set_style_line_rounded(knock_chart, true, LV_PART_ITEMS); // Enable rounded line ends

    // Disable points for a smooth line (remove the dots)
    lv_obj_set_style_size(knock_chart, 0, LV_PART_INDICATOR);

    // Initialize the series with zero values
    for (int i = 0; i < 40; i++) {
        lv_chart_set_next_value(knock_chart, knock_series, 0);
    }

    lv_chart_refresh(knock_chart);  // Refresh the chart to apply changes
}

// Function to create the Knock 1 label
void create_knock_threshold_label(lv_obj_t *parent) {
    // Create a label at the center top of the knock chart for Knock 1 threshold value
    knock_threshold_label = lv_label_create(parent);
    lv_label_set_text(knock_threshold_label, "Knock 1: 0.0"); // Initial value
    lv_obj_align_to(knock_threshold_label, knock_chart, LV_ALIGN_OUT_TOP_MID, 70, -10); // Align on top of the chart
}

// Function to process CAN message 0x101 and update the chart and label
void process_knock_threshold(const twai_message_t *message) {
    if (message->identifier == 0x101) {
        // Ensure there are enough bytes to read (2 bytes starting from offset 1)
        if (message->data_length_code >= 3) {
            // Extract 2 bytes from offset 1, little-endian format
            uint16_t raw_value = (message->data[2] << 8) | message->data[1];

            // Apply the scaling factor
            float knock_threshold = raw_value * 0.1f;

            // Debug log to check the extracted and scaled value
           // ESP_LOGI(TAG, "Raw value: %u, Scaled knock threshold value: %.2f", raw_value, knock_threshold);

            // Ensure knock_threshold is in the 0 to 100 range for graph display
            if (knock_threshold > 100) {
                knock_threshold = 100;  // Cap at 100
            } else if (knock_threshold < 0) {
                knock_threshold = 0;  // Cap at 0
            }

            // Update the chart with the new knock threshold value
            lv_chart_set_next_value(knock_chart, knock_series, (int)knock_threshold);

            // Update the label with the new knock threshold value
            char label_text[32];
            snprintf(label_text, sizeof(label_text), "Knock 1: %.1f", knock_threshold);
            lv_label_set_text(knock_threshold_label, label_text);
            lv_obj_set_style_text_color(knock_threshold_label, THEME_COLOR_TEXT_PRIMARY, LV_PART_MAIN | LV_STATE_DEFAULT);

            // Force refresh the chart and label to update the graph and value display
            lv_chart_refresh(knock_chart);
        } else {
            ESP_LOGE(TAG, "Received CAN message length too short");
        }
    }
}

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, THEME_COLOR_BG, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    create_knock_graph_on_screen2(ui_Screen2);
    create_knock_threshold_label(ui_Screen2);

    // Create Dropdown for Band Pass Frequency
    ui_band_freq_dropdown = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_band_freq_dropdown, 
        "1.22 kHz\n"
        "1.26 kHz\n"
        "1.31 kHz\n"
        "1.35 kHz\n"
        "1.40 kHz\n"
        "1.45 kHz\n"
        "1.51 kHz\n"
        "1.57 kHz\n"
        "1.63 kHz\n"
        "1.71 kHz\n"
        "1.78 kHz\n"
        "1.87 kHz\n"
        "1.96 kHz\n"
        "2.07 kHz\n"
        "2.18 kHz\n"
        "2.31 kHz\n"
        "2.46 kHz\n"
        "2.54 kHz\n"
        "2.62 kHz\n"
        "2.71 kHz\n"
        "2.81 kHz\n"
        "2.92 kHz\n"
        "3.03 kHz\n"
        "3.15 kHz\n"
        "3.28 kHz\n"
        "3.43 kHz\n"
        "3.59 kHz\n"
        "3.76 kHz\n"
        "3.95 kHz\n"
        "4.16 kHz\n"
        "4.39 kHz\n"
        "4.66 kHz\n"
        "4.95 kHz\n"
        "5.12 kHz\n"
        "5.29 kHz\n"
        "5.48 kHz\n"
        "5.68 kHz\n"
        "5.90 kHz\n"
        "6.12 kHz\n"
        "6.37 kHz\n"
        "6.64 kHz\n"
        "6.94 kHz\n"
        "7.27 kHz\n"
        "7.63 kHz\n"
        "8.02 kHz\n"
        "8.46 kHz\n"
        "8.95 kHz\n"
        "9.50 kHz\n"
        "10.12 kHz\n"
        "10.46 kHz\n"
        "10.83 kHz\n"
        "11.22 kHz\n"
        "11.65 kHz\n"
        "12.10 kHz\n"
        "12.60 kHz\n"
        "13.14 kHz\n"
        "13.72 kHz\n"
        "14.36 kHz\n"
        "15.07 kHz\n"
        "15.84 kHz\n"
        "16.71 kHz\n"
        "17.67 kHz\n"
        "18.76 kHz\n"
        "19.98 kHz");
    lv_obj_set_width(ui_band_freq_dropdown, 150);
    lv_obj_set_height(ui_band_freq_dropdown, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_band_freq_dropdown, -245);
    lv_obj_set_y(ui_band_freq_dropdown, -150);
    lv_obj_set_align(ui_band_freq_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_band_freq_dropdown, dropdown_event_handler, LV_EVENT_VALUE_CHANGED, NULL);

    // Create Dropdown for Gain
    ui_gain_dropdown = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_gain_dropdown, 
        "2.000\n"
        "1.882\n"
        "1.778\n"
        "1.684\n"
        "1.600\n"
        "1.523\n"
        "1.455\n"
        "1.391\n"
        "1.333\n"
        "1.280\n"
        "1.231\n"
        "1.185\n"
        "1.143\n"
        "1.063\n"
        "1.000\n"
        "0.944\n"
        "0.895\n"
        "0.850\n"
        "0.810\n"
        "0.773\n"
        "0.739\n"
        "0.708\n"
        "0.680\n"
        "0.654\n"
        "0.630\n"
        "0.607\n"
        "0.586\n"
        "0.567\n"
        "0.548\n"
        "0.500\n"
        "0.471\n"
        "0.444\n"
        "0.421\n"
        "0.400\n"
        "0.381\n"
        "0.364\n"
        "0.348\n"
        "0.333\n"
        "0.320\n"
        "0.308\n"
        "0.296\n"
        "0.286\n"
        "0.276\n"
        "0.267\n"
        "0.258\n"
        "0.250\n"
        "0.236\n"
        "0.222\n"
        "0.211\n"
        "0.200\n"
        "0.190\n"
        "0.182\n"
        "0.174\n"
        "0.167\n"
        "0.160\n"
        "0.154\n"
        "0.148\n"
        "0.143\n"
        "0.138\n"
        "0.133\n"
        "0.129\n"
        "0.125\n"
        "0.118\n"
        "0.111");
    lv_obj_set_width(ui_gain_dropdown, 150);
    lv_obj_set_height(ui_gain_dropdown, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_gain_dropdown, -245);
    lv_obj_set_y(ui_gain_dropdown, -50);
    lv_obj_set_align(ui_gain_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_gain_dropdown, dropdown_event_handler, LV_EVENT_VALUE_CHANGED, NULL);

    // Create Dropdown for Time Constants
    ui_time_constant_dropdown = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_time_constant_dropdown, 
        "40s \n"
        "45 s\n"
        "50 s\n"
        "55 s\n"
        "60 s\n"
        "65 s\n"
        "70 s\n"
        "75 s\n"
        "80 s\n"
        "90 s\n"
        "100 s\n"
        "110 s\n"
        "120 s\n"
        "130 s\n"
        "140 s\n"
        "150 s\n"
        "160 s\n"
        "180 s\n"
        "200 s\n"
        "220 s\n"
        "240 s\n"
        "260 s\n"
        "280 s\n"
        "300 s\n"
        "320 s\n"
        "360 s\n"
        "400 s\n"
        "440 s\n"
        "480 s\n"
        "520 s\n"
        "560 s\n"
        "600 s");
    lv_obj_set_width(ui_time_constant_dropdown, 150);
    lv_obj_set_height(ui_time_constant_dropdown, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_time_constant_dropdown, -245);
    lv_obj_set_y(ui_time_constant_dropdown, 50);
    lv_obj_set_align(ui_time_constant_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_time_constant_dropdown, dropdown_event_handler, LV_EVENT_VALUE_CHANGED, NULL);

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -250);
    lv_obj_set_y(ui_Label1, -200);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "BAND BASS FREQUENCY");
    lv_obj_set_style_text_color(ui_Label1, THEME_COLOR_TEXT_PRIMARY, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -250);
    lv_obj_set_y(ui_Label2, -100);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "GAIN");
    lv_obj_set_style_text_color(ui_Label2, THEME_COLOR_TEXT_PRIMARY, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -250);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "INTEGRATOR TIME CONSTRAINT");
    lv_obj_set_style_text_color(ui_Label3, THEME_COLOR_TEXT_PRIMARY, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -250);
    lv_obj_set_y(ui_Label4, 100);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "OPTION 4");
    lv_obj_set_style_text_color(ui_Label4, THEME_COLOR_TEXT_PRIMARY, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenLeft = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ScreenLeft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_indicator_left_png, NULL);
    lv_imgbtn_set_src(ui_ScreenLeft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_indicator_left_png, NULL);
    lv_imgbtn_set_src(ui_ScreenLeft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ScreenLeft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_indicator_left_png, NULL);
    lv_imgbtn_set_src(ui_ScreenLeft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ScreenLeft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ScreenLeft, 29);
    lv_obj_set_width(ui_ScreenLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ScreenLeft, -369);
    lv_obj_set_y(ui_ScreenLeft, 212);
    lv_obj_set_align(ui_ScreenLeft, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_ScreenLeft, THEME_COLOR_NAV_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ScreenLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_ScreenLeft, THEME_COLOR_NAV_PRESSED, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_ScreenLeft, 200, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScreenRight = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ScreenRight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_indicator_right_png, NULL);
    lv_imgbtn_set_src(ui_ScreenRight, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_indicator_right_png, NULL);
    lv_imgbtn_set_src(ui_ScreenRight, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ScreenRight, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_indicator_right_png, NULL);
    lv_imgbtn_set_src(ui_ScreenRight, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_indicator_right_png, NULL);
    lv_imgbtn_set_src(ui_ScreenRight, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ScreenRight, 29);
    lv_obj_set_width(ui_ScreenRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ScreenRight, 369);
    lv_obj_set_y(ui_ScreenRight, 212);
    lv_obj_set_align(ui_ScreenRight, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_ScreenRight, THEME_COLOR_NAV_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ScreenRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_ScreenRight, THEME_COLOR_NAV_PRESSED, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_ScreenRight, 200, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_ScreenLeft, ui_event_ScreenLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenRight, ui_event_ScreenRight, LV_EVENT_ALL, NULL);
}
