/* AUTO-GENERATED by tools/codegen_widget_inspector.py — DO NOT EDIT.
 *
 * Worst-case rows the on-device inspector can build for one widget in
 * one tab, per control-type pool. Derived from
 * schema/widgets.schema.json so the pools cannot silently fall behind
 * it: a pool smaller than its bound drops fields with no log, which is
 * how half the meter's STYLE tab went missing.
 *
 * These ignore the runtime inspector_get probe and enabled_by, so they
 * over-estimate on purpose. Sizing a pool to its bound makes overflow
 * unreachable rather than merely unlikely.
 */
#pragma once

/* every rendered row (name -> swatch / value label) */
#define WIDGET_FIELDS_MAX_TAB_ROWS       56
/* colour rows */
#define WIDGET_FIELDS_MAX_TAB_COLOR      13
/* stepper / stepper-auto / slider rows */
#define WIDGET_FIELDS_MAX_TAB_INT        29
/* checkbox rows */
#define WIDGET_FIELDS_MAX_TAB_BOOL       8
/* dropdown rows */
#define WIDGET_FIELDS_MAX_TAB_SELECT     3
/* text / textarea / font / number rows */
#define WIDGET_FIELDS_MAX_TAB_TEXT       8
