"""Author per-field `help` text in widgets.schema.json. The editor shows it as a
hover tooltip via the small i icon next to each setting. Keyed widget -> field
-> text. Idempotent; preserves the schema's CRLF + inline-option formatting for
a clean diff. Run both codegens afterward.

Non-ASCII kept to the degree sign only (matches existing labels); everything
else stays ASCII to avoid any emit-path mojibake.
"""
import json, io, re

HELP = {
    "arc": {
        "start_angle_user": "Where the gauge starts, as a clock position in degrees (0 = 3 o'clock, going clockwise). This is the empty end.",
        "sweep_degrees": "How far around the circle the gauge goes. 270 covers most of a circle like a normal gauge; 360 is a full circle.",
        "signal_min": "The reading that shows the gauge empty (the start).",
        "signal_max": "The reading that shows the gauge full (the end).",
        "tick_min": "The first number the marks count from. Usually the same as the empty value.",
        "tick_max": "The last number the marks count up to. Usually the same as the full value.",
        "anchor_enabled": "Fill the gauge out from a set point instead of from the empty end. Handy for gauges that read both ways, like a turbo boost/vacuum gauge that rests at zero.",
        "anchor_value": "The reading the fill grows out from when the option above is on.",
        "anchor_position": "Where that start point sits along the gauge, as a percentage (0 = start, 100 = end).",
        "reverse": "Run the gauge backwards, so the full end becomes the empty end.",
        "smoothing_ms": "Smooths out jumpy readings. Higher is smoother but slower to react; 0 shows the raw, instant value.",
        "arc_width": "How thick the coloured (filled) part of the gauge is.",
        "arc_offset": "Moves the ring in or out from the centre. Use it to stack one gauge inside another.",
        "arc_color": "Colour of the filled part.",
        "bg_arc_color": "Colour of the empty part behind the fill.",
        "bg_arc_width": "How thick the empty background ring is. Make it wider or narrower than the fill for a raised or recessed look.",
        "rounded_ends": "Give the gauge rounded ends instead of flat-cut ones.",
        "fade_fill": "Fade the colour from dim to bright along the filled part, for a glowing look.",
        "lead_edge_enabled": "Add a bright tip that sits at the current reading, like the glowing end of a digital bar.",
        "lead_edge_color": "Colour of that bright tip.",
        "lead_edge_width": "How wide the bright tip is.",
        "arc_image": "Use a picture for the empty background instead of a plain colour.",
        "arc_image_full": "Use a picture for the filled part instead of a plain colour. It's uncovered bit by bit as the reading rises.",
        "redline_color": "Colour of the warning zone (like a rev counter's red zone). Where it starts is set by this reading's high-warning level.",
        "redline_arc_width": "How thick the warning-zone band is.",
        "redline_recolor_fill": "When the reading reaches the warning zone, turn the whole fill that colour - not just the band.",
        "show_ticks": "Show the marks around the gauge, like the lines on a speedometer.",
        "major_tick_step": "How far apart the biggest marks are, in reading value. On a 0-8000 rev counter, 1000 puts a big mark every 1000 RPM.",
        "mid_tick_step": "How far apart the medium marks are. 0 turns them off.",
        "minor_tick_step": "How far apart the smallest marks are. 0 turns them off.",
        "major_tick_width": "How thick the biggest marks are.",
        "mid_tick_width": "How thick the medium marks are.",
        "minor_tick_width": "How thick the smallest marks are.",
        "major_tick_length": "How long the biggest marks are.",
        "mid_tick_length": "How long the medium marks are.",
        "minor_tick_length": "How long the smallest marks are.",
        "major_tick_color": "Colour of the biggest marks.",
        "mid_tick_color": "Colour of the medium marks.",
        "minor_tick_color": "Colour of the smallest marks.",
        "show_tick_labels": "Show numbers next to the biggest marks.",
        "tick_label_font": "Text style and size of those numbers.",
        "tick_label_color": "Colour of those numbers.",
        "label_gap": "How far the numbers sit from the marks.",
        "tick_label_divisor": "Shrink the numbers by dividing them. Set 1000 and a 7000 mark just shows '7' - common on rev counters.",
        "ticks_on_top": "Draw the marks and numbers on top of the fill instead of behind it.",
        "show_value_line": "Show a thin pointer line at the current reading.",
        "value_line_width": "How thick the pointer line is.",
        "value_line_color": "Colour of the pointer line.",
        "value_line_r_mod": "Shorten the pointer line from the outer edge inward.",
        "arc_alerts_enabled": "Change the fill colour when the reading goes too low or too high (set the points below).",
        "arc_low": "At or below this reading, the fill turns the Low colour.",
        "arc_low_color": "Fill colour when the reading is low.",
        "arc_high": "At or above this reading, the fill turns the High colour.",
        "arc_high_color": "Fill colour when the reading is high.",
    },

    "meter": {
        "min": "The reading at the start of the dial.",
        "max": "The reading at the end of the dial.",
        "start_angle_user": "Where the dial starts, as a clock position in degrees (0 = 3 o'clock, going clockwise).",
        "sweep_degrees": "How far around the dial goes. 270 is a normal gauge; 360 is a full circle.",
        "reverse": "Run the dial backwards, so the high reading sits at the start.",
        "anchor_enabled": "Swing the needle out from a set point instead of from the start. Good for gauges that read both ways around zero.",
        "anchor_value": "The reading the needle swings out from when the option above is on.",
        "anchor_position": "Where that point sits along the dial, as a percentage.",
        "show_ticks": "Show the marks around the dial, like the lines on a speedometer.",
        "major_tick_step": "How far apart the biggest marks are, in reading value. On a 0-8000 rev counter, 1000 puts a big mark every 1000 RPM.",
        "mid_tick_step": "How far apart the medium marks are. 0 turns them off.",
        "minor_tick_step": "How far apart the smallest marks are. 0 turns them off.",
        "major_tick_width": "How thick the biggest marks are.",
        "mid_tick_width": "How thick the medium marks are (0 = off).",
        "minor_tick_width": "How thick the smallest marks are.",
        "major_tick_length": "How long the biggest marks are.",
        "mid_tick_length": "How long the medium marks are (0 = off).",
        "minor_tick_length": "How long the smallest marks are.",
        "major_tick_color": "Colour of the biggest marks.",
        "mid_tick_color": "Colour of the medium marks.",
        "minor_tick_color": "Colour of the smallest marks.",
        "show_tick_labels": "Show numbers next to the biggest marks.",
        "tick_label_font": "Text style and size of those numbers.",
        "tick_label_color": "Colour of those numbers.",
        "label_gap": "How far the numbers sit from the marks.",
        "tick_label_divisor": "Shrink the numbers by dividing them. Set 1000 and a 7000 mark just shows '7' - common on rev counters.",
        "redline_enabled": "Show a warning zone, like a rev counter's red zone.",
        "redline_threshold": "The reading where the warning zone starts.",
        "redline_color": "Colour of the warning zone.",
        "redline_show_arc": "Draw a coloured band along the warning zone.",
        "redline_arc_width": "How thick that band is.",
        "redline_arc_r_mod": "Move the warning band in or out from the dial.",
        "redline_recolor_ticks": "Turn the marks inside the warning zone that colour too.",
        "smoothing_ms": "Smooths out jumpy readings. Higher is smoother but slower to react; 0 shows the raw value.",
        "meter_bg_color": "Background colour of the gauge face.",
        "meter_bg_opa": "How solid the gauge face is (0 = see-through, 255 = solid).",
        "bg_image_name": "Use a picture as the gauge face.",
        "border_color": "Colour of the outline around the gauge.",
        "border_width": "Thickness of the outline (0 = none).",
        "border_opa": "How solid the outline is (0-255).",
        "scale_padding": "Move the marks inward from the edge of the gauge.",
        "show_needle": "Show the pointer needle.",
        "needle_width": "How thick the needle is.",
        "needle_color": "Colour of the needle.",
        "needle_r_mod": "Shorten the needle from its outer end.",
        "needle_rear_length": "How far the needle sticks out behind its centre, for a counterweight look.",
        "needle_inner_radius": "Start the needle away from the centre, leaving a gap in the middle.",
        "needle_tip_style": "The shape of the needle's tip.",
        "needle_tip_base_w": "How wide the needle is at its base (leave at auto unless you want to set it).",
        "needle_tip_point_w": "How wide the needle is at its tip.",
        "needle_tip_taper": "How sharply the needle narrows toward the tip.",
        "needle_image_name": "Use a picture as the needle instead of a drawn one.",
        "needle_pivot_x": "Move the needle's centre point left or right.",
        "needle_pivot_y": "Move the needle's centre point up or down.",
        "needle_angle_offset": "Rotate where the needle rests, in degrees.",
        "show_needle_ball": "Show a round hub in the middle of the needle.",
        "needle_ball_size": "How big the hub is.",
        "needle_ball_color": "Colour of the hub.",
    },

    "bar": {
        "label": "Text shown with the bar.",
        "bar_min": "The reading at the empty end of the bar.",
        "bar_max": "The reading at the full end of the bar.",
        "decimals": "How many digits after the decimal point to show.",
        "anchor_enabled": "Fill out from a set point instead of from the end. Good for bars that read both ways around zero.",
        "anchor_value": "The reading the fill grows out from when the option above is on.",
        "anchor_position": "Where that point sits along the bar, as a percentage.",
        "show_bar_value": "Show the number on the bar.",
        "smoothing_ms": "Smooths out jumpy readings. Higher is smoother but slower to react; 0 shows the raw value.",
        "invert_bar_value": "Flip it so a high reading empties the bar instead of filling it.",
        "center_fill": "Fill out from the middle of the bar in both directions.",
        "fill_dir": "Which way the bar fills (left, right, up or down).",
        "bar_in_range_color": "Colour of the bar.",
        "bar_image_full": "Use a picture for the filled part instead of a plain colour.",
        "fill_edge_color": "Colour of the bright tip that sits at the current reading.",
        "indicator_radius": "How rounded the filled part's corners are.",
        "bar_bg_color": "Colour of the empty part behind the fill.",
        "bar_image": "Use a picture for the empty background instead of a plain colour.",
        "bar_radius": "How rounded the whole bar's corners are.",
        "bar_border_width": "Thickness of the outline (0 = none).",
        "bar_border_color": "Colour of the outline.",
        "label_font": "Text style and size of the label.",
        "label_color": "Colour of the label.",
        "value_font": "Text style and size of the number.",
        "value_color": "Colour of the number.",
        "show_ticks": "Show marks along the bar, like the lines on a fuel gauge.",
        "tick_side": "Which side of the bar the marks sit on.",
        "tick_count": "How many marks to show along the bar.",
        "tick_width": "How thick the marks are.",
        "tick_length": "How long the marks are.",
        "tick_color": "Colour of the marks.",
        "bar_alerts_enabled": "Change the bar colour when the reading goes too low or too high (set the points below).",
        "bar_low": "At or below this reading, the bar turns the Low colour.",
        "bar_low_color": "Bar colour when the reading is low.",
        "bar_high": "At or above this reading, the bar turns the High colour.",
        "bar_high_color": "Bar colour when the reading is high.",
        "fill_edge_width": "How wide the bright tip at the current reading is (0 = off).",
    },

    "rpm_bar": {
        "rpm_max": "The highest RPM the bar shows. It fills from 0 up to here.",
        "redline": "The RPM where the red warning zone starts - the bar changes colour past this point.",
        "limiter_value": "The RPM where your rev limiter kicks in - the bar reacts here.",
        "smoothing_ms": "Smooths out jumpy readings. Higher is smoother but slower to react; 0 shows the raw value.",
        "bar_color": "Colour of the bar below the redline.",
        "fill_dir": "Which way the bar fills (left, right, up or down).",
        "bar_bg_color": "Colour of the empty background.",
        "limiter_color": "Colour shown when you hit the limiter.",
        "show_ticks": "Show marks along the bar.",
        "tick_side": "Which side of the bar the marks sit on.",
        "tick_width": "How thick the marks are.",
        "tick_length": "How long the marks are.",
        "tick_color": "Colour of the marks.",
        "limiter_effect": "What happens at the limiter - flash, or just change colour.",
        "flash_speed": "How fast it flashes at the limiter (smaller = faster), in milliseconds.",
    },

    "panel": {
        "label": "The title shown above the number (e.g. COOLANT).",
        "decimals": "How many digits after the decimal point to show.",
        "label_font": "Text style and size of the title.",
        "label_color": "Colour of the title.",
        "value_font": "Text style and size of the number.",
        "value_color": "Colour of the number.",
        "text_align": "Line the text up to the left, centre or right.",
        "label_y_offset": "Nudge the title up or down.",
        "value_y_offset": "Nudge the number up or down.",
        "show_peak": "Also show the highest (or lowest) reading reached, held on screen.",
        "peak_font": "Text style and size of the held reading.",
        "peak_x_offset": "Nudge the held reading left or right.",
        "peak_y_offset": "Nudge the held reading up or down.",
        "show_unit": "Add the unit after the number, like °C or PSI.",
        "unit_size": "How big the unit is next to the number.",
        "custom_text": "Replace the unit with your own text.",
        "custom_text_x_offset": "Nudge that text left or right.",
        "custom_text_y_offset": "Nudge that text up or down.",
        "bg_color": "Background colour of the panel.",
        "bg_opa": "How solid the background is (0 = see-through, 255 = solid).",
        "border_color": "Colour of the outline.",
        "border_width": "Thickness of the outline (0 = none).",
        "border_radius": "How rounded the corners are.",
        "warning_low_enabled": "Warn when the reading drops too low.",
        "warning_low_threshold": "Warn once the reading falls to or below this.",
        "warning_low_color": "The alert colour used when it's too low.",
        "warning_low_apply_label": "Turn the title the alert colour when it's too low.",
        "warning_low_apply_value": "Turn the number the alert colour when it's too low.",
        "warning_low_apply_panel": "Turn the panel's edge/background the alert colour when it's too low.",
        "warning_high_enabled": "Warn when the reading climbs too high.",
        "warning_high_threshold": "Warn once the reading rises to or above this.",
        "warning_high_color": "The alert colour used when it's too high.",
        "warning_high_apply_label": "Turn the title the alert colour when it's too high.",
        "warning_high_apply_value": "Turn the number the alert colour when it's too high.",
        "warning_high_apply_panel": "Turn the panel's edge/background the alert colour when it's too high.",
    },

    "text": {
        "static_text": "Type fixed text to show. Leave blank to show the live reading instead.",
        "decimals": "How many digits after the decimal point when showing a reading.",
        "font": "Text style and size.",
        "text_color": "Text colour.",
        "rotation": "Turn the text on an angle, in degrees.",
    },

    "image": {
        "image_name": "The picture to show.",
        "image_scale": "Resize the picture, as a percentage.",
        "opacity": "How see-through the picture is (0 = invisible, 255 = solid).",
        "recolor": "Tint the whole picture this colour.",
        "recolor_opa": "How strong the tint is (0 = none, 255 = full). Tinting a light icon white can make it disappear.",
    },

    "indicator": {
        "slot": "Which side of the screen this light sits on.",
        "input_source": "What turns the light on - a sensor reading or a built-in source.",
        "color_on": "Colour when the light is on.",
        "opa_on": "How bright it is when on (0-255).",
        "color_off": "Colour when the light is off.",
        "opa_off": "How bright it is when off (0-255).",
        "animation": "Fade smoothly between on and off.",
        "is_momentary": "Only stay on while the signal is active, instead of latching on.",
    },

    "warning": {
        "label": "Text shown on the tile.",
        "active_color": "Tile colour when the warning is on.",
        "active_opa": "How solid the tile is when on (0-255).",
        "inactive_color": "Tile colour when off.",
        "inactive_opa": "How solid the tile is when off (0-255).",
        "radius": "How rounded the tile's corners are.",
        "border_width": "Thickness of the outline (0 = none).",
        "border_color_style": "Colour of the outline.",
        "image_name": "Icon shown on the tile.",
        "image_scale": "Resize the icon, as a percentage.",
        "show_label": "Show the text on the tile.",
        "label_color": "Text colour.",
        "label_font": "Text style and size.",
        "label_y_offset": "Nudge the text up or down.",
        "label_text_align": "Line the text up left, centre or right.",
        "is_momentary": "Only stay on while the signal is active, instead of latching on.",
        "invert_toggle": "Flip it - the warning shows when the signal is OFF.",
    },

    "shape_panel": {
        "shape_type": "The shape to draw.",
        "bg_color": "Fill colour.",
        "bg_opa": "How see-through the fill is (0 = invisible, 255 = solid).",
        "border_color": "Colour of the outline.",
        "border_width": "Thickness of the outline (0 = none).",
        "border_radius": "How rounded the corners are (for rectangles).",
        "shadow_width": "How far the drop shadow spreads (0 = no shadow).",
        "shadow_color": "Colour of the shadow.",
        "shadow_opa": "How dark the shadow is (0-255).",
        "shadow_ofs_x": "Move the shadow left or right.",
        "shadow_ofs_y": "Move the shadow up or down.",
        "bake_into_gauge": "Lock this shape into the background so it draws faster. It won't change while driving - use for decoration only.",
    },

    "line": {
        "orientation": "Which way the line runs (across, up-down, or diagonal).",
        "line_color": "Colour of the line.",
        "line_width": "How thick the line is.",
        "line_opa": "How see-through the line is (0-255).",
        "rounded": "Round the line's ends.",
        "dash_gap": "Gap between dashes (0 = a solid line).",
    },

    "banner": {
        "op": "How the reading is checked to pop up the message (over, under, equal to, or within a range).",
        "threshold": "The value the reading is checked against.",
        "range_min": "The bottom of the range (when using 'within a range').",
        "range_max": "The top of the range (when using 'within a range').",
        "text": "The message to show when it pops up.",
        "text_align": "Line the message up left, centre or right.",
        "bg_color": "Background colour.",
        "bg_opa": "How solid the background is (0-255).",
        "text_color": "Colour of the message.",
        "font": "Text style and size.",
        "border_width": "Thickness of the outline (0 = none).",
        "border_color": "Colour of the outline.",
        "radius": "How rounded the corners are.",
    },

    "shift_light": {
        "signal_name": "What drives the lights - usually RPM.",
        "range_min": "The reading where the first light comes on.",
        "range_max": "The reading where every light is on.",
        "led_count": "How many lights in the row.",
        "flash_threshold": "The reading where the whole row flashes - your shift point.",
        "flash_speed": "How fast it flashes (smaller = faster), in milliseconds.",
        "fill_mode": "How the lights fill up as the reading rises.",
        "color_low": "Colour of the first (low) lights.",
        "color_mid": "Colour of the middle lights.",
        "color_high": "Colour of the top lights.",
        "color_off": "Colour of lights that are off.",
        "threshold_mid": "The reading where the lights switch to the middle colour.",
        "threshold_high": "The reading where the lights switch to the top colour.",
        "led_spacing": "Gap between the lights.",
        "led_width": "How wide each light is (0 = fit automatically).",
        "led_height": "How tall each light is (0 = fit automatically).",
        "border_radius": "How rounded each light's corners are.",
    },

    "toggle": {
        "label": "Text shown on the switch.",
        "show_label": "Show the text.",
        "signal_on_threshold": "The reading at or above which the switch shows as ON.",
        "tx_can_id": "Advanced: the CAN message ID this switch sends. Leave alone unless you're wiring it to the car's CAN bus.",
        "tx_bit_start": "Advanced: which bit in the CAN message to set.",
        "tx_bit_length": "Advanced: how many bits to send.",
        "tx_endian": "Advanced: byte order of the sent value.",
        "tx_rate_hz": "Advanced: how often to resend the message, per second (0 = only when it changes).",
        "image_name": "Icon shown on the switch.",
        "active_color": "Colour when ON.",
        "active_opa": "How solid it is when ON (0-255).",
        "inactive_color": "Colour when OFF.",
        "inactive_opa": "How solid it is when OFF (0-255).",
        "label_color": "Text colour.",
        "font": "Text style and size.",
        "label_align": "Line the text up left, centre or right.",
        "label_x": "Nudge the text left or right.",
        "label_y": "Nudge the text up or down.",
    },

    "button": {
        "label": "Text shown on the button.",
        "show_label": "Show the text.",
        "latch": "Stay on after a press (toggle) instead of only while held.",
        "tx_can_id": "Advanced: the CAN message ID this button sends. Leave alone unless wiring it to the car's CAN bus.",
        "tx_bit_start": "Advanced: which bit in the CAN message to set.",
        "tx_bit_length": "Advanced: how many bits to send.",
        "tx_endian": "Advanced: byte order of the sent value.",
        "tx_rate_hz": "Advanced: how often to resend while held, per second (0 = send once).",
        "tx_send_release": "Advanced: also send a message when you let go.",
        "bg_color": "Colour of the button.",
        "text_color": "Text colour.",
        "pressed_color": "Colour while you're pressing it.",
        "border_radius": "How rounded the corners are.",
        "font": "Text style and size.",
        "label_align": "Line the text up left, centre or right.",
        "label_x": "Nudge the text left or right.",
        "label_y": "Nudge the text up or down.",
        "image_name": "Icon shown on the button.",
    },

    "pathbar": {
        "min": "The reading at the start of the bar.",
        "max": "The reading at the end of the bar.",
        "redline": "The reading where the warning zone starts along the bar.",
        "lit_color": "Colour of the filled part.",
        "dim_color": "Colour of the empty part.",
        "dim_opa": "How see-through the empty part is (0-255).",
        "band_width": "How thick the bar is.",
        "rounded": "Round the bar's ends.",
        "fade_fill": "Fade the colour from dim to bright along the filled part, for a glowing look.",
        "lead_edge_enabled": "Add a bright tip at the current reading, like a glowing bar end.",
        "lead_edge_color": "Colour of that bright tip.",
        "lead_edge_width": "How wide the bright tip is.",
        "redline_color": "Colour of the warning zone.",
        "redline_recolor_ticks": "Turn the marks inside the warning zone that colour too.",
        "shape": "Pick a ready-made shape (straight, L-bend, 45°, or the curved J-hook tacho) sized to fit the box, or Custom to draw your own path.",
        "orientation": "Which way the bar runs and fills.",
        "corner_radius": "How big the rounded corner of the bend is (or the bevel, on the 45° shape).",
        "hook_angle": "J-hook shape only: how far the curve sweeps. 90 is a quarter turn, 180 a half turn.",
        "smooth": "Custom shapes only: smooth your drawn points into a flowing curve.",
        "show_ticks": "Show marks along the bar.",
        "major_tick_step": "How far apart the biggest marks are, in reading value.",
        "minor_tick_step": "How far apart the smaller marks are. 0 turns them off.",
        "major_tick_width": "How thick the biggest marks are.",
        "tick_width": "How thick the smaller marks are.",
        "major_tick_len": "How long the biggest marks are.",
        "tick_len": "How long the smaller marks are.",
        "major_tick_color": "Colour of the biggest marks.",
        "tick_color": "Colour of the smaller marks.",
        "show_labels": "Show numbers next to the biggest marks.",
        "label_font": "Text style and size of those numbers.",
        "label_color": "Colour of those numbers.",
        "label_gap": "How far the numbers sit from the bar.",
        "tick_label_divisor": "Shrink the numbers by dividing them (1000 shows 7000 as '7').",
        "smoothing_ms": "Smooths out jumpy readings. Higher is smoother but slower to react; 0 shows the raw value.",
    },
}

PATH = "schema/widgets.schema.json"
S = json.load(io.open(PATH, encoding="utf-8"))
widgets = S.get("widgets") or S.get("widget_types")
wmap = {w["name"]: w for w in widgets}

applied = 0
missing = []
for wname, fields in HELP.items():
    w = wmap.get(wname)
    if not w:
        missing.append(wname); continue
    fmap = {f["name"]: f for f in w["fields"]}
    for fn, text in fields.items():
        f = fmap.get(fn)
        if not f:
            missing.append(wname + "." + fn); continue
        if f.get("help") != text:
            f["help"] = text; applied += 1

txt = json.dumps(S, ensure_ascii=False, indent=2)
txt = re.sub(r'\{\s*\n\s*"value": ([^\n]+?),\s*\n\s*"label": ([^\n]+?)\s*\n\s*\}',
             r'{ "value": \1, "label": \2 }', txt)
with io.open(PATH, "w", encoding="utf-8", newline="\r\n") as fp:
    fp.write(txt + "\n")

print("applied/updated %d help string(s)" % applied)
if missing:
    print("MISSING (no such widget/field):", missing)
tot = sum(len(w["fields"]) for w in widgets)
cov = sum(1 for w in widgets for f in w["fields"] if f.get("help"))
print("overall coverage: %d/%d fields have help" % (cov, tot))
for w in widgets:
    h = sum(1 for f in w["fields"] if f.get("help"))
    flag = "" if h == len(w["fields"]) else "   <-- INCOMPLETE"
    print("  %-12s %d/%d%s" % (w["name"], h, len(w["fields"]), flag))
