"""Author per-field `help` text in widgets.schema.json. The editor shows it as a
hover tooltip via the small i icon next to each setting. Keyed widget -> field
-> text. Idempotent; preserves the schema's CRLF + inline-option formatting for
a clean diff. Run both codegens afterward.

Non-ASCII kept to the degree sign only (matches existing labels); everything
else stays ASCII to avoid any emit-path mojibake.
"""
import json, io, re

HELP = {
    "arc": {
        "start_angle_user": "Where the arc begins, in degrees (0° = 3 o'clock, increasing clockwise). The fill grows from here.",
        "sweep_degrees": "How far the arc travels from the start angle. 270 = a classic three-quarter gauge, 360 = full circle.",
        "signal_min": "Channel value mapped to the empty (start) end of the arc.",
        "signal_max": "Channel value mapped to the full (end) end of the arc.",
        "tick_min": "First value the tick scale covers. Usually matches Signal Min; set differently to label only part of the range.",
        "tick_max": "Last value the tick scale covers. Usually matches Signal Max.",
        "anchor_enabled": "Grow the fill outward from a fixed anchor value instead of from the start - ideal for centre-zero gauges like boost/vacuum.",
        "anchor_value": "The value the fill grows out from when Anchor Curve is on.",
        "anchor_position": "Where the anchor sits along the arc, as a percent of its length (0 = start, 100 = end).",
        "reverse": "Flip the fill so it grows from the high end toward the low end.",
        "smoothing_ms": "Damping time for fill/needle movement. Higher = smoother but laggier; 0 = instant, raw response.",
        "arc_width": "Thickness of the lit (value) arc, in pixels.",
        "arc_offset": "Shifts the whole ring in/out from the widget centre, in pixels. Use to nest concentric arcs.",
        "arc_color": "Colour of the lit (value) portion of the arc.",
        "bg_arc_color": "Colour of the unlit track behind the fill.",
        "bg_arc_width": "Thickness of the background track. Make it wider or narrower than the fill for a recessed or raised look.",
        "rounded_ends": "Round the ends of the fill and track instead of flat-cut.",
        "lead_edge_color": "Colour of the leading-edge marker.",
        "lead_edge_width": "Width of the leading-edge marker, in pixels.",
        "arc_image": "Use an image as the track instead of a solid colour.",
        "arc_image_full": "Use an image as the lit fill instead of a solid colour - revealed progressively as the value rises.",
        "redline_color": "Colour of the redline band. Its position comes from the bound channel's high-warning threshold.",
        "redline_arc_width": "Thickness of the redline band arc.",
        "redline_recolor_fill": "When the value enters the redline zone, recolour the whole fill (not just the band) to the redline colour.",
        "show_ticks": "Draw tick marks around the arc.",
        "major_tick_step": "Value distance between major (largest) ticks. e.g. 1000 on a 0-8000 tach = a major tick every 1000.",
        "mid_tick_step": "Value distance between medium ticks. 0 = no medium tier.",
        "minor_tick_step": "Value distance between minor (smallest) ticks. 0 = no minor tier.",
        "major_tick_width": "Thickness of the major ticks, in pixels.",
        "mid_tick_width": "Thickness of the medium ticks, in pixels.",
        "minor_tick_width": "Thickness of the minor ticks, in pixels.",
        "major_tick_length": "Length of the major ticks, in pixels.",
        "mid_tick_length": "Length of the medium ticks, in pixels.",
        "minor_tick_length": "Length of the minor ticks, in pixels.",
        "major_tick_color": "Colour of the major ticks.",
        "mid_tick_color": "Colour of the medium ticks.",
        "minor_tick_color": "Colour of the minor ticks.",
        "show_tick_labels": "Draw numeric labels at the major ticks.",
        "tick_label_font": "Font (family:size) for the tick number labels.",
        "tick_label_color": "Colour of the tick number labels.",
        "label_gap": "Gap between the tick ring and the number labels, in pixels. Larger pushes labels toward the centre.",
        "tick_label_divisor": "Divide label values before display. 1000 -> a 7000 tick reads '7' (e.g. RPM x1000).",
        "ticks_on_top": "Draw ticks and labels above the fill instead of behind it.",
        "show_value_line": "Draw a thin radial line pointing at the current value.",
        "value_line_width": "Thickness of the value line, in pixels.",
        "value_line_color": "Colour of the value line.",
        "value_line_r_mod": "Trim the value line's length inward from the outer edge, in pixels.",
        "arc_alerts_enabled": "Recolour the fill when the value crosses the thresholds below - independent of the channel redline.",
        "arc_low": "At or below this value the fill uses the Low Color.",
        "arc_low_color": "Fill colour when the value is at or below the Low Threshold.",
        "arc_high": "At or above this value the fill uses the High Color.",
        "arc_high_color": "Fill colour when the value is at or above the High Threshold.",
    },

    "meter": {
        "min": "Channel value at the start of the scale.",
        "max": "Channel value at the end of the scale.",
        "start_angle_user": "Where the scale begins, in degrees (0° = 3 o'clock, increasing clockwise).",
        "sweep_degrees": "How far the scale sweeps from the start angle. 270 = a three-quarter gauge, 360 = full circle.",
        "reverse": "Reverse the scale so the high value sits at the start.",
        "anchor_enabled": "Sweep the needle from a fixed anchor value instead of from the start - good for centre-zero gauges.",
        "anchor_value": "The value the needle sweeps out from when Anchor Curve is on.",
        "anchor_position": "Where the anchor sits along the scale, as a percent of its length.",
        "show_ticks": "Draw tick marks around the dial.",
        "major_tick_step": "Value distance between major (largest) ticks. e.g. 1000 on a 0-8000 tach.",
        "mid_tick_step": "Value distance between medium ticks. 0 = no medium tier.",
        "minor_tick_step": "Value distance between minor ticks. 0 = no minor tier.",
        "major_tick_width": "Thickness of the major ticks, in pixels.",
        "mid_tick_width": "Thickness of the medium ticks, in pixels (0 = off).",
        "minor_tick_width": "Thickness of the minor ticks, in pixels.",
        "major_tick_length": "Length of the major ticks, in pixels.",
        "mid_tick_length": "Length of the medium ticks, in pixels (0 = off).",
        "minor_tick_length": "Length of the minor ticks, in pixels.",
        "major_tick_color": "Colour of the major ticks.",
        "mid_tick_color": "Colour of the medium ticks.",
        "minor_tick_color": "Colour of the minor ticks.",
        "show_tick_labels": "Draw numeric labels at the major ticks.",
        "tick_label_font": "Font (family:size) for the number labels.",
        "tick_label_color": "Colour of the number labels.",
        "label_gap": "Gap between the tick ring and the number labels, in pixels.",
        "tick_label_divisor": "Divide label values before display. 1000 -> a 7000 tick reads '7' (e.g. RPM x1000).",
        "redline_enabled": "Turn on the redline warning zone.",
        "redline_threshold": "Value where the redline zone begins.",
        "redline_color": "Colour of the redline zone.",
        "redline_show_arc": "Draw a coloured arc along the redline zone (in addition to any tick recolouring).",
        "redline_arc_width": "Thickness of the redline arc, in pixels.",
        "redline_arc_r_mod": "Move the redline arc in/out from the scale, in pixels.",
        "redline_recolor_ticks": "Recolour ticks inside the redline zone to the redline colour.",
        "smoothing_ms": "Damping time for needle movement. Higher = smoother but laggier; 0 = instant.",
        "meter_bg_color": "Gauge face background colour.",
        "meter_bg_opa": "Gauge face background opacity (0 = transparent, 255 = solid).",
        "bg_image_name": "Image drawn as the gauge face.",
        "border_color": "Border colour around the gauge.",
        "border_width": "Border thickness, in pixels (0 = none).",
        "border_opa": "Border opacity (0-255).",
        "scale_padding": "Inset the tick scale from the gauge edge, in pixels.",
        "show_needle": "Draw the needle.",
        "needle_width": "Needle thickness, in pixels.",
        "needle_color": "Needle colour.",
        "needle_r_mod": "Trim the needle length inward from the outer edge, in pixels.",
        "needle_rear_length": "Length of the needle's tail behind the pivot, in pixels.",
        "needle_inner_radius": "Distance from the pivot where the needle starts, in pixels (hollow centre).",
        "needle_tip_style": "Shape of the needle tip.",
        "needle_tip_base_w": "Width of the needle at its base, in pixels (auto unless set).",
        "needle_tip_point_w": "Width of the needle at its tip, in pixels.",
        "needle_tip_taper": "How sharply the needle narrows from base to tip, in percent.",
        "needle_image_name": "Use an image as the needle instead of a drawn shape.",
        "needle_pivot_x": "Move the needle pivot horizontally, in pixels.",
        "needle_pivot_y": "Move the needle pivot vertically, in pixels.",
        "needle_angle_offset": "Rotate the needle's resting angle, in degrees.",
        "show_needle_ball": "Draw a hub circle at the needle pivot.",
        "needle_ball_size": "Diameter of the hub circle, in pixels.",
        "needle_ball_color": "Colour of the hub circle.",
    },

    "bar": {
        "label": "Text label shown with the bar.",
        "bar_min": "Channel value at the empty end of the bar.",
        "bar_max": "Channel value at the full end of the bar.",
        "decimals": "Decimal places for the shown value (overrides the channel default).",
        "anchor_enabled": "Grow the fill from a fixed anchor value instead of from the end - good for centre-zero bars.",
        "anchor_value": "The value the fill grows out from when Anchor Curve is on.",
        "anchor_position": "Where the anchor sits along the bar, as a percent of its length.",
        "show_bar_value": "Print the numeric value on the bar.",
        "smoothing_ms": "Damping time for bar movement. Higher = smoother but laggier; 0 = instant.",
        "invert_bar_value": "Invert the fill so a high value empties the bar.",
        "center_fill": "Fill outward from the centre of the bar in both directions.",
        "fill_dir": "Which direction the bar fills from (left, right, up or down).",
        "bar_in_range_color": "Colour of the bar fill in the normal range.",
        "bar_image_full": "Use an image as the fill instead of a solid colour.",
        "fill_edge_color": "Colour of the bright marker that rides the fill's leading edge.",
        "indicator_radius": "Corner rounding of the fill, in pixels.",
        "bar_bg_color": "Colour of the empty track behind the fill.",
        "bar_image": "Use an image as the track instead of a solid colour.",
        "bar_radius": "Corner rounding of the whole bar, in pixels.",
        "bar_border_width": "Bar border thickness, in pixels (0 = none).",
        "bar_border_color": "Bar border colour.",
        "label_font": "Font (family:size) for the label.",
        "label_color": "Label colour.",
        "value_font": "Font (family:size) for the value.",
        "value_color": "Value colour.",
        "show_ticks": "Draw tick marks along the bar.",
        "tick_side": "Which side of the bar the ticks sit on.",
        "tick_count": "Number of tick marks along the bar.",
        "tick_width": "Thickness of the ticks, in pixels.",
        "tick_length": "Length of the ticks, in pixels.",
        "tick_color": "Colour of the ticks.",
        "bar_alerts_enabled": "Recolour the bar when the value crosses the thresholds below.",
        "bar_low": "At or below this value the bar uses the Low Color.",
        "bar_low_color": "Bar colour at or below the Low Threshold.",
        "bar_high": "At or above this value the bar uses the High Color.",
        "bar_high_color": "Bar colour at or above the High Threshold.",
    },

    "rpm_bar": {
        "rpm_max": "Top of the bar's range, in RPM. The bar fills from 0 to here.",
        "redline": "RPM where the redline zone begins - the bar recolours past this point.",
        "limiter_value": "RPM at which the rev-limiter effect kicks in.",
        "smoothing_ms": "Damping time for bar movement. Higher = smoother but laggier; 0 = instant.",
        "bar_color": "Colour of the bar fill below the redline.",
        "fill_dir": "Which direction the bar fills from (left, right, up or down).",
        "bar_bg_color": "Colour of the empty track behind the bar.",
        "limiter_color": "Colour used when the limiter RPM is reached.",
        "show_ticks": "Draw tick marks along the bar.",
        "tick_side": "Which side of the bar the ticks sit on.",
        "tick_width": "Thickness of the ticks, in pixels.",
        "tick_length": "Length of the ticks, in pixels.",
        "tick_color": "Colour of the ticks.",
        "limiter_effect": "What happens at the limiter RPM (e.g. flash or solid colour).",
        "flash_speed": "Flash interval at the limiter, in milliseconds. Lower = faster.",
    },

    "panel": {
        "label": "Header text shown above the value (e.g. 'COOLANT').",
        "decimals": "Decimal places for the value (overrides the channel default).",
        "label_font": "Font (family:size) for the header label.",
        "label_color": "Colour of the header label.",
        "value_font": "Font (family:size) for the main value.",
        "value_color": "Colour of the main value.",
        "text_align": "Horizontal alignment of the text (left, centre, right).",
        "label_y_offset": "Nudge the header label up/down, in pixels.",
        "value_y_offset": "Nudge the value up/down, in pixels.",
        "show_peak": "Show a held peak (or min) marker alongside the live value.",
        "peak_font": "Font (family:size) for the peak marker.",
        "peak_x_offset": "Nudge the peak marker horizontally, in pixels.",
        "peak_y_offset": "Nudge the peak marker vertically, in pixels.",
        "show_unit": "Append the channel's unit (e.g. °C) after the value.",
        "unit_size": "Size of the unit suffix relative to the value.",
        "custom_text": "Override the unit suffix with your own text.",
        "custom_text_x_offset": "Nudge the unit text horizontally, in pixels.",
        "custom_text_y_offset": "Nudge the unit text vertically, in pixels.",
        "bg_color": "Panel background colour.",
        "bg_opa": "Panel background opacity (0 = transparent, 255 = solid).",
        "border_color": "Panel border colour.",
        "border_width": "Panel border thickness, in pixels (0 = none).",
        "border_radius": "Corner rounding, in pixels.",
        "warning_low_enabled": "Turn on the low-value alert.",
        "warning_low_threshold": "When the value drops to or below this, the low alert fires.",
        "warning_low_color": "Alert colour applied when the low threshold is crossed.",
        "warning_low_apply_label": "Apply the low-alert colour to the header label.",
        "warning_low_apply_value": "Apply the low-alert colour to the value.",
        "warning_low_apply_panel": "Apply the low-alert colour to the panel border/background.",
        "warning_high_enabled": "Turn on the high-value alert.",
        "warning_high_threshold": "When the value rises to or above this, the high alert fires.",
        "warning_high_color": "Alert colour applied when the high threshold is crossed.",
        "warning_high_apply_label": "Apply the high-alert colour to the header label.",
        "warning_high_apply_value": "Apply the high-alert colour to the value.",
        "warning_high_apply_panel": "Apply the high-alert colour to the panel border/background.",
    },

    "text": {
        "static_text": "Fixed text to display. Leave blank to show the bound channel's value instead.",
        "decimals": "Decimal places when showing a channel value.",
        "font": "Font (family:size).",
        "text_color": "Text colour.",
        "rotation": "Rotate the text, in degrees.",
    },

    "image": {
        "image_name": "The image to display.",
        "image_scale": "Scale the image, in percent.",
        "opacity": "Image opacity (0 = transparent, 255 = solid).",
        "recolor": "Tint the image with this colour.",
        "recolor_opa": "Strength of the tint (0 = none, 255 = full). Tinting a light icon to white can make it vanish.",
    },

    "indicator": {
        "slot": "Which side of the screen this indicator occupies (left or right).",
        "input_source": "What drives the indicator - a bound signal or an internal source.",
        "color_on": "Colour when active/on.",
        "opa_on": "Opacity when active (0-255).",
        "color_off": "Colour when inactive/off.",
        "opa_off": "Opacity when inactive (0-255).",
        "animation": "Fade the transition between on and off.",
        "is_momentary": "Active only while the signal is asserted (vs latched on).",
    },

    "warning": {
        "label": "Text shown on the warning tile.",
        "active_color": "Tile colour when the warning is active.",
        "active_opa": "Tile opacity when active (0-255).",
        "inactive_color": "Tile colour when inactive.",
        "inactive_opa": "Tile opacity when inactive (0-255).",
        "radius": "Corner rounding of the tile, in pixels.",
        "border_width": "Tile border thickness, in pixels (0 = none).",
        "border_color_style": "Tile border colour.",
        "image_name": "Icon image shown on the tile.",
        "image_scale": "Scale the icon, in percent.",
        "show_label": "Show the text label on the tile.",
        "label_color": "Label colour.",
        "label_font": "Font (family:size) for the label.",
        "label_y_offset": "Nudge the label up/down, in pixels.",
        "label_text_align": "Horizontal alignment of the label.",
        "is_momentary": "Active only while the signal is asserted (vs latched on).",
        "invert_toggle": "Treat the signal as inverted - active when the signal is off.",
    },

    "shape_panel": {
        "shape_type": "The shape to draw.",
        "bg_color": "Fill colour.",
        "bg_opa": "Fill opacity (0 = transparent, 255 = solid).",
        "border_color": "Border colour.",
        "border_width": "Border thickness, in pixels (0 = none).",
        "border_radius": "Corner rounding, in pixels (rectangles).",
        "shadow_width": "Drop-shadow spread, in pixels (0 = none).",
        "shadow_color": "Drop-shadow colour.",
        "shadow_opa": "Drop-shadow opacity (0-255).",
        "shadow_ofs_x": "Offset the shadow horizontally, in pixels.",
        "shadow_ofs_y": "Offset the shadow vertically, in pixels.",
        "bake_into_gauge": "Render this static shape into the gauge background for better performance (it won't change at runtime).",
    },

    "line": {
        "orientation": "Direction of the line (horizontal, vertical or diagonal).",
        "line_color": "Line colour.",
        "line_width": "Line thickness, in pixels.",
        "line_opa": "Line opacity (0-255).",
        "rounded": "Round the line ends.",
        "dash_gap": "Gap between dashes, in pixels (0 = solid line).",
    },

    "banner": {
        "op": "How the value is compared to the threshold to trigger the banner (e.g. >, <, =, in range).",
        "threshold": "The value the operator compares against.",
        "range_min": "Lower bound when the operator is 'in range'.",
        "range_max": "Upper bound when the operator is 'in range'.",
        "text": "Message shown when the banner triggers.",
        "text_align": "Horizontal alignment of the message.",
        "bg_color": "Banner background colour.",
        "bg_opa": "Banner background opacity (0-255).",
        "text_color": "Message text colour.",
        "font": "Font (family:size) for the message.",
        "border_width": "Banner border thickness, in pixels (0 = none).",
        "border_color": "Banner border colour.",
        "radius": "Corner rounding, in pixels.",
    },

    "shift_light": {
        "signal_name": "The channel that drives the LED bar (usually RPM).",
        "range_min": "Value at which the first LED lights.",
        "range_max": "Value at which every LED is lit.",
        "led_count": "Number of LEDs in the bar.",
        "flash_threshold": "Value at/above which the whole bar flashes (the shift point).",
        "flash_speed": "Flash interval, in milliseconds. Lower = faster.",
        "fill_mode": "How the LEDs light up as the value rises (e.g. left-to-right, or by zone).",
        "color_low": "Colour of the LEDs in the low zone.",
        "color_mid": "Colour of the LEDs in the mid zone.",
        "color_high": "Colour of the LEDs in the high zone.",
        "color_off": "Colour of unlit LEDs.",
        "threshold_mid": "Value where the LEDs switch to the mid colour.",
        "threshold_high": "Value where the LEDs switch to the high colour.",
        "led_spacing": "Gap between LEDs, in pixels.",
        "led_width": "Width of each LED, in pixels (0 = auto-fit).",
        "led_height": "Height of each LED, in pixels (0 = auto-fit).",
        "border_radius": "Corner rounding of each LED, in pixels.",
    },

    "toggle": {
        "label": "Text shown on the toggle.",
        "show_label": "Show the text label.",
        "signal_on_threshold": "Bound value at or above which the toggle reads as ON.",
        "tx_can_id": "CAN frame ID this toggle transmits on when switched.",
        "tx_bit_start": "Start bit of the transmitted value within the frame.",
        "tx_bit_length": "Number of bits transmitted.",
        "tx_endian": "Byte order of the transmitted value.",
        "tx_rate_hz": "How often the frame is re-sent, in Hz (0 = send once on change).",
        "image_name": "Icon shown on the toggle.",
        "active_color": "Colour when ON.",
        "active_opa": "Opacity when ON (0-255).",
        "inactive_color": "Colour when OFF.",
        "inactive_opa": "Opacity when OFF (0-255).",
        "label_color": "Label colour.",
        "font": "Font (family:size) for the label.",
        "label_align": "Horizontal alignment of the label.",
        "label_x": "Nudge the label horizontally, in pixels.",
        "label_y": "Nudge the label vertically, in pixels.",
    },

    "button": {
        "label": "Text shown on the button.",
        "show_label": "Show the text label.",
        "latch": "Toggle on each press (latched) instead of momentary.",
        "tx_can_id": "CAN frame ID this button transmits on when pressed.",
        "tx_bit_start": "Start bit of the transmitted value within the frame.",
        "tx_bit_length": "Number of bits transmitted.",
        "tx_endian": "Byte order of the transmitted value.",
        "tx_rate_hz": "How often the frame is re-sent while held, in Hz (0 = send once).",
        "tx_send_release": "Also send a frame when the button is released.",
        "bg_color": "Button background colour.",
        "text_color": "Button label colour.",
        "pressed_color": "Background colour while the button is held.",
        "border_radius": "Corner rounding, in pixels.",
        "font": "Font (family:size) for the label.",
        "label_align": "Horizontal alignment of the label.",
        "label_x": "Nudge the label horizontally, in pixels.",
        "label_y": "Nudge the label vertically, in pixels.",
        "image_name": "Icon shown on the button.",
    },

    "pathbar": {
        "min": "Channel value at the start of the path.",
        "max": "Channel value at the end of the path.",
        "redline": "Value where the redline zone begins along the path.",
        "lit_color": "Colour of the lit (value) portion of the band.",
        "dim_color": "Colour of the unlit portion of the band.",
        "dim_opa": "Opacity of the unlit portion (0-255).",
        "band_width": "Thickness of the band, in pixels.",
        "rounded": "Round the band ends.",
        "lead_edge_color": "Colour of the leading-edge marker.",
        "lead_edge_width": "Width of the leading-edge marker, in pixels.",
        "redline_color": "Colour of the redline zone.",
        "redline_recolor_ticks": "Recolour ticks inside the redline zone to the redline colour.",
        "orientation": "Direction the path runs and fills.",
        "corner_radius": "Corner rounding for preset bends (L-Bend etc.), in pixels.",
        "show_ticks": "Draw the tick scale along the path.",
        "major_tick_step": "Value distance between major ticks.",
        "minor_tick_step": "Value distance between minor ticks. 0 = no minor ticks.",
        "major_tick_width": "Thickness of the major ticks, in pixels.",
        "tick_width": "Thickness of the minor ticks, in pixels.",
        "major_tick_len": "Length of the major ticks, in pixels.",
        "tick_len": "Length of the minor ticks, in pixels.",
        "major_tick_color": "Colour of the major ticks.",
        "tick_color": "Colour of the minor ticks.",
        "show_labels": "Draw numeric labels at the major ticks.",
        "label_font": "Font (family:size) for the number labels.",
        "label_color": "Colour of the number labels.",
        "label_gap": "Gap between the path and the number labels, in pixels.",
        "tick_label_divisor": "Divide label values before display (e.g. 1000 -> RPM x1000).",
        "smoothing_ms": "Damping time for fill movement. Higher = smoother but laggier; 0 = instant.",
    },
}

PATH = "schema/widgets.schema.json"
S = json.load(io.open(PATH, encoding="utf-8"))
widgets = S.get("widgets") or S.get("widget_types")
wmap = {w["name"]: w for w in widgets}

applied = 0
missing = []
for wname, fields in HELP.items():
    w = wmap.get(wname)
    if not w:
        missing.append(wname); continue
    fmap = {f["name"]: f for f in w["fields"]}
    for fn, text in fields.items():
        f = fmap.get(fn)
        if not f:
            missing.append(wname + "." + fn); continue
        if f.get("help") != text:
            f["help"] = text; applied += 1

txt = json.dumps(S, ensure_ascii=False, indent=2)
txt = re.sub(r'\{\s*\n\s*"value": ([^\n]+?),\s*\n\s*"label": ([^\n]+?)\s*\n\s*\}',
             r'{ "value": \1, "label": \2 }', txt)
with io.open(PATH, "w", encoding="utf-8", newline="\r\n") as fp:
    fp.write(txt + "\n")

print("applied/updated %d help string(s)" % applied)
if missing:
    print("MISSING (no such widget/field):", missing)
tot = sum(len(w["fields"]) for w in widgets)
cov = sum(1 for w in widgets for f in w["fields"] if f.get("help"))
print("overall coverage: %d/%d fields have help" % (cov, tot))
for w in widgets:
    h = sum(1 for f in w["fields"] if f.get("help"))
    flag = "" if h == len(w["fields"]) else "   <-- INCOMPLETE"
    print("  %-12s %d/%d%s" % (w["name"], h, len(w["fields"]), flag))
