/*
 * boot_assets.c — Seed firmware-embedded default files into LittleFS.
 *
 * The RDM logo is embedded in the firmware binary via EMBED_FILES. On boot
 * (after LittleFS is mounted), we check whether /lfs/images/RDM.rdmimg
 * exists; if not, we write the embedded copy so the default layout always
 * has a logo to render. This also means a factory reset that wipes
 * /lfs/images/ is automatically recovered on the next boot.
 */
#include "boot_assets.h"

#include "esp_log.h"
#include "layout_manager.h"  /* LFS_BASE_PATH */

#include <stdio.h>
#include <string.h>
#include <strings.h>         /* strcasecmp */
#include <sys/stat.h>

static const char *TAG = "boot_assets";

#define IMAGES_DIR LFS_BASE_PATH "/images"
#define FONTS_DIR  LFS_BASE_PATH "/fonts"

/* Symbols generated by EMBED_FILES "embed/RDM.rdmimg" in main/CMakeLists.txt. */
extern const uint8_t rdm_rdmimg_start[] asm("_binary_RDM_rdmimg_start");
extern const uint8_t rdm_rdmimg_end[]   asm("_binary_RDM_rdmimg_end");

/* Built-in TTF fonts embedded via EMBED_FILES (see main/CMakeLists.txt). Seeded
 * to /lfs/fonts/ with display-friendly (spaced) names so font_manager loads them
 * as scalable families "Montserrat" / "Fugaz One" / "Manrope Bold". */
extern const uint8_t montserrat_ttf_start[]   asm("_binary_montserrat_ttf_start");
extern const uint8_t montserrat_ttf_end[]     asm("_binary_montserrat_ttf_end");
extern const uint8_t fugaz_one_ttf_start[]    asm("_binary_fugaz_one_ttf_start");
extern const uint8_t fugaz_one_ttf_end[]      asm("_binary_fugaz_one_ttf_end");
extern const uint8_t manrope_bold_ttf_start[] asm("_binary_manrope_bold_ttf_start");
extern const uint8_t manrope_bold_ttf_end[]   asm("_binary_manrope_bold_ttf_end");

static const struct {
	const char    *path;
	const uint8_t *start;
	const uint8_t *end;
} s_builtin_fonts[] = {
	{ FONTS_DIR "/Montserrat.ttf",   montserrat_ttf_start,   montserrat_ttf_end   },
	{ FONTS_DIR "/Fugaz One.ttf",    fugaz_one_ttf_start,    fugaz_one_ttf_end    },
	{ FONTS_DIR "/Manrope Bold.ttf", manrope_bold_ttf_start, manrope_bold_ttf_end },
};

static esp_err_t _ensure_images_dir(void)
{
	struct stat st;
	if (stat(IMAGES_DIR, &st) == 0)
		return ESP_OK;
	if (mkdir(IMAGES_DIR, 0755) != 0) {
		ESP_LOGE(TAG, "mkdir(%s) failed", IMAGES_DIR);
		return ESP_FAIL;
	}
	ESP_LOGI(TAG, "Created %s", IMAGES_DIR);
	return ESP_OK;
}

static esp_err_t _ensure_fonts_dir(void)
{
	struct stat st;
	if (stat(FONTS_DIR, &st) == 0)
		return ESP_OK;
	if (mkdir(FONTS_DIR, 0755) != 0) {
		ESP_LOGE(TAG, "mkdir(%s) failed", FONTS_DIR);
		return ESP_FAIL;
	}
	ESP_LOGI(TAG, "Created %s", FONTS_DIR);
	return ESP_OK;
}

static esp_err_t _write_if_missing(const char *path, const uint8_t *data, size_t len)
{
	struct stat st;
	if (stat(path, &st) == 0 && st.st_size > 0) {
		ESP_LOGD(TAG, "%s already present (%ld bytes) — leaving alone",
		         path, (long)st.st_size);
		return ESP_OK;
	}

	FILE *f = fopen(path, "wb");
	if (!f) {
		ESP_LOGE(TAG, "fopen(%s) failed", path);
		return ESP_FAIL;
	}
	size_t written = fwrite(data, 1, len, f);
	fclose(f);
	if (written != len) {
		ESP_LOGE(TAG, "short write to %s: %u/%u", path,
		         (unsigned)written, (unsigned)len);
		return ESP_FAIL;
	}
	ESP_LOGI(TAG, "Seeded %s (%u bytes)", path, (unsigned)len);
	return ESP_OK;
}

esp_err_t boot_assets_seed_defaults(void)
{
	esp_err_t err = _ensure_images_dir();
	if (err != ESP_OK)
		return err;

	size_t rdm_len = (size_t)(rdm_rdmimg_end - rdm_rdmimg_start);
	esp_err_t logo_err =
		_write_if_missing(BOOT_ASSETS_RDM_LOGO_PATH, rdm_rdmimg_start, rdm_len);

	/* Seed the built-in scalable TTF fonts. Best-effort: a font failing to
	 * seed shouldn't block boot or the logo result. */
	if (_ensure_fonts_dir() == ESP_OK) {
		for (size_t i = 0; i < sizeof(s_builtin_fonts) / sizeof(s_builtin_fonts[0]); i++) {
			size_t len = (size_t)(s_builtin_fonts[i].end - s_builtin_fonts[i].start);
			_write_if_missing(s_builtin_fonts[i].path, s_builtin_fonts[i].start, len);
		}
	}

	return logo_err;
}

bool boot_assets_is_protected_image(const char *name)
{
	if (!name) return false;
	return strcmp(name, BOOT_ASSETS_RDM_LOGO_NAME) == 0;
}

bool boot_assets_is_protected_font(const char *name)
{
	if (!name) return false;
	/* Family names of the embedded scalable fonts (see s_builtin_fonts). */
	static const char *const kProtected[] = {
		"Montserrat", "Fugaz One", "Manrope Bold",
	};
	for (size_t i = 0; i < sizeof(kProtected) / sizeof(kProtected[0]); i++) {
		if (strcasecmp(name, kProtected[i]) == 0) return true;
	}
	return false;
}

bool boot_assets_is_protected_layout(const char *name)
{
	if (!name) return false;
	return strcmp(name, "default") == 0;
}
