/*
 * boot_assets.c — Seed firmware-embedded default files into LittleFS.
 *
 * The RDM logo is embedded in the firmware binary via EMBED_FILES. On boot
 * (after LittleFS is mounted), we check whether /lfs/images/RDM.rdmimg
 * exists; if not, we write the embedded copy so the default layout always
 * has a logo to render. This also means a factory reset that wipes
 * /lfs/images/ is automatically recovered on the next boot.
 */
#include "boot_assets.h"

#include "esp_log.h"
#include "layout_manager.h"  /* LFS_BASE_PATH */

#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

static const char *TAG = "boot_assets";

#define IMAGES_DIR LFS_BASE_PATH "/images"

/* Symbols generated by EMBED_FILES "embed/RDM.rdmimg" in main/CMakeLists.txt. */
extern const uint8_t rdm_rdmimg_start[] asm("_binary_RDM_rdmimg_start");
extern const uint8_t rdm_rdmimg_end[]   asm("_binary_RDM_rdmimg_end");

static esp_err_t _ensure_images_dir(void)
{
	struct stat st;
	if (stat(IMAGES_DIR, &st) == 0)
		return ESP_OK;
	if (mkdir(IMAGES_DIR, 0755) != 0) {
		ESP_LOGE(TAG, "mkdir(%s) failed", IMAGES_DIR);
		return ESP_FAIL;
	}
	ESP_LOGI(TAG, "Created %s", IMAGES_DIR);
	return ESP_OK;
}

static esp_err_t _write_if_missing(const char *path, const uint8_t *data, size_t len)
{
	struct stat st;
	if (stat(path, &st) == 0 && st.st_size > 0) {
		ESP_LOGD(TAG, "%s already present (%ld bytes) — leaving alone",
		         path, (long)st.st_size);
		return ESP_OK;
	}

	FILE *f = fopen(path, "wb");
	if (!f) {
		ESP_LOGE(TAG, "fopen(%s) failed", path);
		return ESP_FAIL;
	}
	size_t written = fwrite(data, 1, len, f);
	fclose(f);
	if (written != len) {
		ESP_LOGE(TAG, "short write to %s: %u/%u", path,
		         (unsigned)written, (unsigned)len);
		return ESP_FAIL;
	}
	ESP_LOGI(TAG, "Seeded %s (%u bytes)", path, (unsigned)len);
	return ESP_OK;
}

esp_err_t boot_assets_seed_defaults(void)
{
	esp_err_t err = _ensure_images_dir();
	if (err != ESP_OK)
		return err;

	size_t rdm_len = (size_t)(rdm_rdmimg_end - rdm_rdmimg_start);
	return _write_if_missing(BOOT_ASSETS_RDM_LOGO_PATH, rdm_rdmimg_start, rdm_len);
}

bool boot_assets_is_protected_image(const char *name)
{
	if (!name) return false;
	return strcmp(name, BOOT_ASSETS_RDM_LOGO_NAME) == 0;
}
