// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Dashboard Design 8.3.11

#include "ui.h"
#include "core/lv_event.h"
#include "ui_helpers.h"
#include "screens/splash_screen.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_RPM_Label;
lv_obj_t * ui_RPM_Value;
lv_obj_t * ui_Speed_Label;
lv_obj_t * ui_SPEED_Value;
lv_obj_t * ui_Gear_Panel;

lv_obj_t * ui_GEAR_Value;
lv_obj_t * ui_GEAR_Icon;
lv_obj_t * ui_Panel_1;
lv_obj_t * ui_Panel_1_Label;
lv_obj_t * ui_Panel_1_Value;
lv_obj_t * ui_Panel_2;
lv_obj_t * ui_Panel_2_Label;
lv_obj_t * ui_Panel_2_Value;
lv_obj_t * ui_Panel_3;
lv_obj_t * ui_Panel_3_Label;
lv_obj_t * ui_Panel_3_Value;
lv_obj_t * ui_Panel_4;
lv_obj_t * ui_Panel_4_Label;
lv_obj_t * ui_Panel_4_Value;
lv_obj_t * ui_Panel_5;
lv_obj_t * ui_Panel_5_Label;
lv_obj_t * ui_Panel_5_Value;
lv_obj_t * ui_Panel_6;
lv_obj_t * ui_Panel_6_Label;
lv_obj_t * ui_Panel_6_Value;
lv_obj_t * ui_Panel_7;
lv_obj_t * ui_Panel_7_Label;
lv_obj_t * ui_Panel_7_Value;
lv_obj_t * ui_Panel_8;
lv_obj_t * ui_Panel_8_Label;
lv_obj_t * ui_Panel_8_Value;
lv_obj_t * ui_Centre_Logo;
lv_obj_t * ui_Indicator_Left;
lv_obj_t * ui_Indicator_Right;
lv_obj_t * ui_Icon_1;
lv_obj_t * ui_Icon_2;
lv_obj_t * ui_Icon_3;
lv_obj_t * ui_Icon_4;
lv_obj_t * ui_Bar_1;
lv_obj_t * ui_Bar_1_Label;
lv_obj_t * ui_Bar_1_Minimim;
lv_obj_t * ui_Bar_1_Maximum;
lv_obj_t * ui_Bar_2;
lv_obj_t * ui_Bar_2_Label;
lv_obj_t * ui_Bar_2_Minimum;
lv_obj_t * ui_Bar_2_Maximum;
lv_obj_t * ui_ODO;
lv_obj_t * ui_ODO_Value;
lv_obj_t * ui_Trip;
lv_obj_t * ui_Trip_Value;
lv_obj_t * ui_Fuel_Avg;
lv_obj_t * ui_Fuel_Avg_Value;
lv_obj_t * ui_Fuel_Inst;
lv_obj_t * ui_Fuel_Inst_Value;
void ui_event_Menu_Button(lv_event_t * e);
lv_obj_t * ui_Menu_Button;
lv_obj_t * ui_Menu_Label;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Slider3;
lv_obj_t * ui_Slider4;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Switch4;
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Colour_Scheme_Button_Label;
void ui_event_ScreenLeft(lv_event_t * e);
lv_obj_t * ui_ScreenLeft;
void ui_event_ScreenRight(lv_event_t * e);
lv_obj_t * ui_ScreenRight;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
void ui_event_Panel2(lv_event_t * e);
lv_obj_t * ui_Background;
lv_obj_t * ui_Box_1;
lv_obj_t * ui_Box_2;
lv_obj_t * ui_Box_3;
lv_obj_t * ui_Box_4;
lv_obj_t * ui_Box_5;
lv_obj_t * ui_Box_6;
lv_obj_t * ui_Box_7;
lv_obj_t * ui_Box_8;
lv_obj_t * ui_Arc_1;
lv_obj_t * ui_Arc_2;
lv_obj_t * ui_Arc_3;
lv_obj_t * ui_Arc_4;
lv_obj_t * ui_Arc_5;
lv_obj_t * ui_Arc_6;
lv_obj_t * ui_Arc_7;
lv_obj_t * ui_Arc_8;
lv_obj_t * ui_Box_Barrier;
lv_obj_t * ui_Main_RPM_Circle;
lv_obj_t * ui_Second_RPM_Circle;
lv_obj_t * ui_Third_RPM_Circle;
lv_obj_t * ui_Fourth_RPM_Circle;
lv_obj_t * ui_Fifth_RPM_Circle;
lv_obj_t * ui_Label_1;
lv_obj_t * ui_Label_2;
lv_obj_t * ui_Label_3;
lv_obj_t * ui_Label_4;
lv_obj_t * ui_Label_5;
lv_obj_t * ui_Label_6;
lv_obj_t * ui_Label_7;
lv_obj_t * ui_Label_8;
lv_obj_t * ui_Bar_1;
lv_obj_t * ui_Bar_2;
lv_obj_t * ui_Bar_3;
lv_obj_t * ui_Bar_4;
lv_obj_t * ui_Bar_5;
lv_obj_t * ui_Bar_6;
lv_obj_t * ui_Bar_7;
lv_obj_t * ui_Bar_8;
lv_obj_t * ui_Value_1;
lv_obj_t * ui_Value_2;
lv_obj_t * ui_Value_3;
lv_obj_t * ui_Value_4;
lv_obj_t * ui_Value_5;
lv_obj_t * ui_Value_6;
lv_obj_t * ui_Value_7;
lv_obj_t * ui_Value_8;
lv_obj_t * ui_Speed_Value;
lv_obj_t * ui_Kmh;
lv_obj_t * ui_RDM_Logo;
lv_obj_t * ui_Indicator_Left;
lv_obj_t * ui_Indicator_Right;
lv_obj_t * ui_Unit_1;
lv_obj_t * ui_Unit_2;
lv_obj_t * ui_Unit_3;
lv_obj_t * ui_Unit_4;
lv_obj_t * ui_Unit_5;
lv_obj_t * ui_Unit_6;
lv_obj_t * ui_Unit_7;
lv_obj_t * ui_Unit_8;
lv_obj_t * ui_RPM_Panel_1;
lv_obj_t * ui_RPM_Panel_2;
lv_obj_t * ui_RPM_Value;
lv_obj_t * ui_RPM_Label;
lv_obj_t * ui_RPM_Panel_Block;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_RPM_Base_1;
lv_obj_t * ui_RPM_Base_2;
lv_obj_t * ui_RPM_Base_3;
lv_obj_t * ui_RPM_Base_4;
lv_obj_t * ui_Warning_1;
lv_obj_t * ui_Warning_2;
lv_obj_t * ui_Warning_3;
lv_obj_t * ui_Warning_4;
lv_obj_t * ui_Warning_5;
lv_obj_t * ui_Warning_6;
lv_obj_t * ui_Warning_7;
lv_obj_t * ui_Warning_8;
lv_obj_t * ui_Warning_2_Label;
lv_obj_t * ui_Warning_4_Label;
lv_obj_t * ui_Warning_6_Label;
lv_obj_t * ui_Warning_8_Label;
lv_obj_t * ui_Redline_Indicator_1;
lv_obj_t * ui_Redline_Indicator_2;
lv_obj_t * ui_Redline_Box_1;
lv_obj_t * ui_Redline_Box_2;
lv_obj_t * ui_Daihatsu_Logo;
lv_obj_t * ui_RDM_Border;
lv_obj_t * ui_RDM_Main;
lv_obj_t * ui_RDM_Logo_Text;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_gauge_v_3_background_trial[1] = {&ui_img_gauge_v0_3_background_trial_png};
const lv_img_dsc_t * ui_imgset_rpm_indicator_png[1] = {&ui_img_rpm_indicator_png};

// Removed duplicate type definitions - now defined in ui_Screen3.h

void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
//void ui_event_Menu_Button(lv_event_t * e)
//{
//    lv_event_code_t event_code = lv_event_get_code(e);
//    if(event_code == LV_EVENT_LONG_PRESSED) {
//        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen2_screen_init);
//    }
//}
void ui_event_ScreenLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_ScreenRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                             true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    show_splash_screen();
}
