// Originally generated by SquareLine Studio (1.4.2, LVGL 8.3.11).
// Project name: Dashboard Design 8.3.11
//
// Trimmed 2026-04-27 to drop dead Screen1/Screen2/Screen4 storage and
// event handlers. Only Screen3 (the live dashboard) remains. If you
// regenerate from SquareLine and re-import, remember to re-trim.

#include "ui.h"
#include "core/lv_event.h"
#include "ui_helpers.h"
#include "screens/splash_screen.h"
#include "ui_styles.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;

// MENU button — used by Screen3 long-press handlers
lv_obj_t * ui_Menu_Button;
lv_obj_t * ui_Menu_Label;

lv_obj_t * ui_Background;
lv_obj_t * ui_Box_1;
lv_obj_t * ui_Box_2;
lv_obj_t * ui_Box_3;
lv_obj_t * ui_Box_4;
lv_obj_t * ui_Box_5;
lv_obj_t * ui_Box_6;
lv_obj_t * ui_Box_7;
lv_obj_t * ui_Box_8;
lv_obj_t * ui_Arc_1;
lv_obj_t * ui_Arc_2;
lv_obj_t * ui_Arc_3;
lv_obj_t * ui_Arc_4;
lv_obj_t * ui_Arc_5;
lv_obj_t * ui_Arc_6;
lv_obj_t * ui_Arc_7;
lv_obj_t * ui_Arc_8;
lv_obj_t * ui_Box_Barrier;
lv_obj_t * ui_Main_RPM_Circle;
lv_obj_t * ui_Second_RPM_Circle;
lv_obj_t * ui_Third_RPM_Circle;
lv_obj_t * ui_Fourth_RPM_Circle;
lv_obj_t * ui_Fifth_RPM_Circle;
lv_obj_t * ui_Label_1;
lv_obj_t * ui_Label_2;
lv_obj_t * ui_Label_3;
lv_obj_t * ui_Label_4;
lv_obj_t * ui_Label_5;
lv_obj_t * ui_Label_6;
lv_obj_t * ui_Label_7;
lv_obj_t * ui_Label_8;
lv_obj_t * ui_Bar_1;
lv_obj_t * ui_Bar_2;
lv_obj_t * ui_Bar_3;
lv_obj_t * ui_Bar_4;
lv_obj_t * ui_Bar_5;
lv_obj_t * ui_Bar_6;
lv_obj_t * ui_Bar_7;
lv_obj_t * ui_Bar_8;
lv_obj_t * ui_Value_1;
lv_obj_t * ui_Value_2;
lv_obj_t * ui_Value_3;
lv_obj_t * ui_Value_4;
lv_obj_t * ui_Value_5;
lv_obj_t * ui_Value_6;
lv_obj_t * ui_Value_7;
lv_obj_t * ui_Value_8;
lv_obj_t * ui_RDM_Logo;
lv_obj_t * ui_Indicator_Left;
lv_obj_t * ui_Indicator_Right;
lv_obj_t * ui_Unit_1;
lv_obj_t * ui_Unit_2;
lv_obj_t * ui_Unit_3;
lv_obj_t * ui_Unit_4;
lv_obj_t * ui_Unit_5;
lv_obj_t * ui_Unit_6;
lv_obj_t * ui_Unit_7;
lv_obj_t * ui_Unit_8;
lv_obj_t * ui_RPM_Panel_1;
lv_obj_t * ui_RPM_Panel_2;
lv_obj_t * ui_RPM_Value;
lv_obj_t * ui_RPM_Label;
lv_obj_t * ui_RPM_Panel_Block;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_RPM_Base_1;
lv_obj_t * ui_RPM_Base_2;
lv_obj_t * ui_RPM_Base_3;
lv_obj_t * ui_RPM_Base_4;
lv_obj_t * ui_Warning_1;
lv_obj_t * ui_Warning_2;
lv_obj_t * ui_Warning_3;
lv_obj_t * ui_Warning_4;
lv_obj_t * ui_Warning_5;
lv_obj_t * ui_Warning_6;
lv_obj_t * ui_Warning_7;
lv_obj_t * ui_Warning_8;
lv_obj_t * ui_Warning_2_Label;
lv_obj_t * ui_Warning_4_Label;
lv_obj_t * ui_Warning_6_Label;
lv_obj_t * ui_Warning_8_Label;
lv_obj_t * ui_Redline_Indicator_1;
lv_obj_t * ui_Redline_Indicator_2;
lv_obj_t * ui_Redline_Box_1;
lv_obj_t * ui_Redline_Box_2;
lv_obj_t * ui_Daihatsu_Logo;
lv_obj_t * ui_RDM_Border;
lv_obj_t * ui_RDM_Main;
lv_obj_t * ui_RDM_Logo_Text;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_gauge_v_3_background_trial[1] = {&ui_img_gauge_v0_3_background_trial_png};
const lv_img_dsc_t * ui_imgset_rpm_indicator_png[1] = {&ui_img_rpm_indicator_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// FUNCTIONS ////////////////////

void ui_init(void)
{
    ui_styles_init();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                             true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    show_splash_screen();
}
